# Executive Summary {-}

## Background {-}

Gentrification and displacement shape the neighborhoods of King County, Washington’s cities and unincorporated urban communities in profound and complex ways. While many parts of America struggle to overcome depopulation and disinvestment, over the past two decades the residents of King County have experienced a set of challenges that come with growth: rising costs of living, ballooning commute times, and housing costs that have grown much faster than most incomes [@king_county_2016_2016]. Gentrification – a term that generally refers to the alteration of a neighborhood’s character in response to changes in the socioeconomic makeup of its residents, the appreciation of real estate values, and new investment by public and private actors – has occurred in many of King County’s neighborhoods during this period of regional growth. While the revitalization of neighborhoods that suffer the costs of persistent poverty is an outcome worth pursuing, it is necessary for policymakers to acknowledge that throughout history many such efforts have instead lead to the displacement of the residents and businesses from these neighborhoods. In King County and throughout the US, marginalized groups including communities of color and low-income communities have born a disproportionate amount of the pressures of urban growth, resulting in social fragmentation and diminished economic opportunity that have intergenerational consequences [@fullilove_root_2016].	

The project began in 2016 as an initiative of the Communities of Opportunity (COO) Evaluation and Advisory Data Workgroup (EAG), which had identified involuntary displacement as a critical but missing indicator of community well-being. The project team started as a collaboration between Futurewise and Puget Sound Sage but later shifted to an intentional partnership between Futurewise and the White Center Community Development Association (WCCDA). All of the project’s partners made important contributions to the work but the insight and perspective of WCCDA were particularly instrumental in enabling the team to adapt the project’s indicators to more closely reflect the conditions on the ground.

The goals of this project are to identify which neighborhoods in King County are experiencing gentrification (or are at risk of gentrifying) and to describe how far along in the process these gentrifying neighborhoods are so that appropriate anti-displacement policies can be implemented. The concept of a “neighborhood change typology” that is actionable and connects to anti-displacement policies comes directly from the work of Dr. @bates_gentrification_2013 [p.9]. Importantly (although perhaps counter-intuitively), this project does not try to measure the number of displaced households, nor does it try to predict displacement rates. While those two data points would be useful information and would fit nicely into the COO “headline indicator” framework, this project’s literature review suggests that there is not yet a methodologically-sound way to measure them at the project’s geographic scale (i.e., all census tracts within King County). The project team intends for the typology information to be used by community-serving organizations in gentrifying neighborhoods as they organize their members to demand displacement mitigation and community restoration policies from the local government. 

In addition to presenting the project’s typology results, this report also shares findings about the importance of conducting gentrification/displacement research in a mutually-accountable partnership between external partners (e.g., Futurewise) and community-based organizations (e.g., WCCDA). The value of including community members and trusted community-based organizations early in the process is explained in the report’s process findings section, as are the project team’s lessons learned about committing to equitable partnership practices and fixing mistakes made along the way. These findings are included because of the project team’s commitment to transparency and so that future efforts might build on this project’s lessons learned.



## Guidance & Limitations {-}

The results of this project should be interpreted and used with caution. Academic researchers, corporations, and governments all have a history of using data analysis in ways that disempower marginalized communities, and it is important to the project team and to all participants in the Communities of Opportunity program that the findings of this project are not misused in this manner [@coalition_of_communities_of_color_leading_2018; @jolivette_research_2015; @townsend_cities_2015]. The following limitations should be considered when interpreting the project’s results and findings:

**The neighborhood types identified by this project do not represent the experience of everyone in each neighborhood.** 
They should not be used to undermine the validity of the lived experience of any individual or group. This project does not include the type of qualitative data that could reflect the experience of being displaced from a gentrifying neighborhood, nor does it provide a quantitative measure of displacement itself. 

**Data are not neutral; they reflect the systemic biases and power dynamics of the individuals or groups that produce them.** 
This project uses data that are publicly available for all neighborhoods in King County, but these data are published by public institutions that have their own priorities and mandates. Decisions about which data to collect and how the collection takes place reflect the priorities of public agencies like the US Census Bureau and the King County Tax Assessor’s Office, and it should not be assumed that their priorities always align with those of the communities most impacted by displacement.^[While lots of good social science research has been done using data from these sources, it is critical that researchers, community members, and policymakers understand and acknowledge the limitations of such data before using them to influence policy decisions] The absence of a frequently-updated, county-wide source of rent prices exemplifies the potentially misaligned priorities between the needs of groups that are susceptible to displacement and the priorities of public institutions.

**This approach uses a relatively small number of indicators to describe the stage of gentrification that neighborhoods are experiencing.**
The project team’s choice to use fewer indicators makes the results more scruitable but also limits the ability to identify different types of gentrification. It is important to understand that the results do not measure the amount of displacement that is occurring nor do they predict how much may occur. 

**This method does not include a way to add contextual data from the communities that are being displaced to refine its typology classification.**
Simply put, if a neighborhood is experiencing gentrification and displacement but those changes are not captured in US Census or Assessor’s Office data then this model will be wrong because it only “knows about” a small set of indicators. If used to inform public policy, the project’s results should complement the results of direct community engagement - not replace them.

**This project’s reliance on relative measures might discount the impact of absolute changes.**
While the median and quintile values provide a useful baseline for comparing the County’s tracts, this approach risks underestimating the impacts of region-wide growth. For instance, if most neighborhoods are experiencing rising housing costs while household incomes remain flat then residents will experience pressure to relocate. In this scenario the comparison of one neighborhood to the rest may be less important than the measurement of absolute change.

**Several technical limitations should also be considered when reading this report.**
For a project attempting to describe a localized, fast-moving process like gentrification, the following limitations are significant and important to acknowledge:

  - The use of survey data from samples of populations at the census tract scale introduces geographic abstraction and statistical uncertainty. Tracts are small, arbitrarily-defined units of geography that often don’t align with familiar neighborhood boundaries. Groups of people with disparate experiences may end up grouped together in the same tract, resulting in data that doesn’t reflect the actual experiences of most of the tract’s population. 
  - The use of statistical sampling increases the uncertainty of the results because this method relies on a relatively small number of survey responses to represent the entire population of a tract. The uncertainty is reduced by combining survey results from different years (e.g., a five-year span of time like 2013 - 2017), but this introduces another limitation: the multi-year span data are more “outdated” and do not fully reflect any recent changes that may have occurred. 

Given these limitations, the project team suggests that the results be understood as an incomplete depiction of where and how gentrification is occurring in King County and that they should be used with appropriate caution. The team hopes that this project will be understood as imperfect attempt to simplify a complex socioeconomic process in order to identify appropriate public policy solutions that can be acted on quickly. **The results of this project should be interpreted not as definitive facts but rather as systematically-derived starting points for discussions between impacted communities and policymakers.** The findings should not be used as a substitute for direct engagement with impacted communities but they may help contextualize such efforts and point toward potential solutions.

## Process Findings {-}

  1. **The people from the communities most impacted by inequities are the ones who best understand the challenges that they face. They must, therefore, play a meaningful role in deciding what solutions to pursue.**<br><br>
  2. **Involving community members and staff from community-based organizations during the ground-truthing workshops played a critical role in the project team’s effort to identify representative indicators. Ground truthing earlier in the project would have made the process more efficient.**<br><br>
  3. **Equitable, well-resourced, and accountable partnerships between researchers/consultants and community-based organizations/community members are necessary when conducting research that aims describe historically-marginalized communities.**<br><br>

## Typology Findings {-}

  1. **Over 30% of the County’s neighborhoods are either experiencing gentrification or are susceptible to it.**<br><br>
  2. **The vast majority of Communities of Opportunity (COO) neighborhoods show signs of gentrification but the specific stages of gentrification vary.**<br><br>
  3. **Each COO community has at least one neighborhood undergoing the “dynamic” stage of gentrification that is associated with ongoing involuntary displacement**<br><br>


 