
# Introduction

## Project History

This project was undertaken at a time when King County was experiencing both economic and population growth.^[Between 1985 and 2015, King County's population grew by 25% (1.4M to 2.1M) and it is expected to grow to 2.3M by 2031 [@king_county_2016_2016]] As with any growing region, the costs and benefits of this growth have not been experienced equally or equitably by the County’s residents. The government of King County, in partnership with the Seattle Foundation, formed a partnership and began implementing the Communities of Opportunity (COO) program with the goal of “address[ing] economic and racial inequities through place-based work and systemic change”.^[To learn more information about COO visit the program's [website](https://www.coopartnerships.org/about-coo)]

Two of COO’s signature strategies (the practice data-driven policy making and the creation of peer-based learning communities) were exemplified by a group of placed-based organizations that met regularly to discuss the challenges and opportunities of working with community data. Known as the Evaluation and Advisory Data Workgroup (EAG)^[The name was initially just "The COO Data Workgroup" but it changed in 2018 to reflect the COO program's focus on internal evaluation], this body provided the inspiration and motivation for the project that would become the “COO Neighborhood Change Typology Report”. At a meeting in early 2016, EAG participants discussed the four outcome areas that COO had identified^[These include health, housing, economic opportunity, and community connections] and the “headline indicators” of these different topics. The group felt that progress was being made on the tracking of most indicators with one glaring exception: involuntary displacement. While everyone in the group had stories of neighbors and clients who were feeling displacement pressure (or had already moved because of it), the participants noted a lack of comprehensive data confirming these lived experiences. The group decided to explore how this problem might be addressed, a process which led to the formation of a subgroup and, ultimately, the creation of this report.


### Timeline {-}

```{r intro-timeline, fig.asp=.5, fig.width=6, dpi = 300,  fig.align = 'left', out.width = '100%'}

timline_image <- image_read("images/project-timeline-leftalign-lowres.png")  

p1 <- image_ggplot(timline_image)
p1 <- p1 +  
  labs(x = NULL, y = NULL,
       title = "COO Neighborhood Change Typology - Project Timeline",
       subtitle = "",
caption = wrapper('Note: The "ground-truthing" workshops,led by Puget Sound Sage, were conducted in White Center, Rainier Valley, and Tukwila.'))  +
  theme_void_nct
p1  


```


### Stage One: Pilot Project, 2016 - 2017 {-}

Between the project’s start in 2016 and the publication of this report in early 2019, there have been several “stages” of work. The first might be described as the “Pilot Project” and it included many stages of its own: the formation of the project team; a review of gentrification and displacement literature; consultation with experts on demographic and real estate data; the development of a preliminary model and results; testing the veracity of these results by comparing them with community members’ lived experiences at “ground-truthing” workshops; and the periodic sharing of progress updates with the EAG.

The ground-truthing workshops, led by Puget Sound Sage, asked members of the three COO communities to describe their experiences of neighborhood change and compare them to the description provided by the Neighborhood Change Typology model.^[This was an earlier version of the model that used a different set of indicators from those used in the model presented in the Results section of this report.] The information shared by workshop participants strongly suggested that the model under-represented the degree of gentrification and potential displacement risk in the COO community neighborhoods, particularly in White Center.

The Pilot Project ended in January 2017 with a presentation to a group of COO stakeholders that included EAG members as well as members of the program’s system change committee and staff from some of COO’s place-based partner organizations. This presentation turned out to be a critically important milestone for the project. The results of the Neighborhood Change Typology method suggested that some parts of Seattle’s Rainier Valley neighborhood and the cities of Seatac and Tukwila^[These two cities were treated as a single place-based “community” in the COO program] were at-risk for gentrification (and displacement) and that the unincorporated community of White Center was not. These findings did not match the lived experience of many of the members of those three communities who had shared examples of on-going gentrification and displacement in the “ground-truthing” workshops. Inaccurate characterizations of communities can negatively impact marginalized communities by undermining their efforts to advocate for public resources and to hold policy makers accountable for addressing disparities. In the case of White Center, these inaccurate preliminary results also had the potential to be “weaponized” by opponents of affordable housing and other equitable community development efforts. Because of these implications, the project team requested additional time and funding to troubleshoot the model and gather data that better reflects the lived experiences of the community members through directly; this additional work was conducted in collaboration with the WCCDA.  

### Stage Two: Hiatus, 2017 - 2018 {-}

The next stage of the project was a 12-month period of no activity that stretched from March 2017 to March 2018. This gap in progress was largely due to the COO program’s internal reorganization work that occurred during this time period.

### Stage Three: Collaborative Revision, 2018 - 2019 {-}

In early summer of 2018, the project team reconvened and began working on a revision. Because the Pilot Phase preliminary results were most inaccurate and potentially damaging for White Center, the revision process focused on improving the model’s characterization of that community. Unfortunately, time and resource constraints prevented the team from expanding to include representatives from Rainier Valley, Seatac, and Tukwila, who could have provided important contextual information to guide the revision process.

Unlike the Pilot, the third stage was structured as a direct collaboration between Futurewise and the WCCDA to form the project team that would finalize the work. Futurewise took the lead on exploring alternative indicators that might improve the project’s model of neighborhood change and the WCCDA provided their expertise on the specific displacement-related challenges that the members of their community faced (and continue to face). The collaborative process involved many meetings in which the WCCDA staff offered invaluable input that guided the search for more-representative indicators. While higher-quality renter data was identified as a priority early in the process, it ultimately became clear that these data do not exist at the county-wide scale required by the project’s method. Nevertheless, the information that the WCCDA provided clarified the limitations inherent in both the original and revised method and led the team to emphasize these limitations in this report. Additionally, this partnership led to productive discussions between the two groups about the challenging limitations that are present in “institutional data” and how these limitations reflect the priorities of America’s dominant culture as reflected in local governments’ land use policies.

Unlike the Pilot phase, the revision did not include a series of ground-truthing workshops. While such workshops would have provided important feedback and vetting for the revised model, they were precluded by the project’s budgetary constraints. The revised Neighborhood Typology Results were presented to the COO EAG in February 2019, who suggested several improvements in how this project can be described to community members and made useful to community-based organizations. A consensus was reached that the neighborhood typology results by themselves provide an incomplete picture and that they must be complemented by contextual information that comes from the impacted communities themselves.


## Defining Gentrification & Displacement

Terms like "neighborhood change", "gentrification", and "displacement" have become increasingly commonplace in the popular discourse about American urban life but this doesn't mean that there is broad agreement on what they mean. To the contrary, the academic literature on this subject contains a passionate debate around the definitions of these words as well as the forces that cause them. This project benefits from the scholarship of researchers like Dr. Lisa Bates, who developed the method that this project is modeled after, and Dr. Miriam Zuk; who, along with her colleagues, produced a comprehensive literature review on these subjects [@bates_gentrification_2013; @miriam_zuk_gentrification_2015].

### Influential Works {-}

Rather than attempting to summarize the wide spectrum of research on these topics, this report highlights the specific pieces of literature that contributed most to the authors’ understanding of gentrification, displacement, and how the two relate. 

First and foremost, Dr. Bates’ 2013 report titled “Gentrification and Displacement Study: Implementing an Equitable Inclusive Development Strategy in the Context of Gentrification” provides an excellent overview of the scholarship before laying out a clear, reproducible method of “operationalizing” a "market-conscious" theory of gentrification. Bates’ work itself builds on a 2005 article by Dr. Lance Freeman which introduced a focused set of socioeconomic and real estate indicators to measure gentrification [@freeman_displacement_2005]. 

In addition to defining the “neighborhood change typology” model, Bates frames her analysis as a tool for selecting public policies that will promote equitable development rather than exacerbate displacement. She unpacks the public sector’s role in gentrification and prescribes the following steps to the City of Portland: adopt a “market-conscious” strategy involving the monitoring of housing market indicators; create regulations and incentives to “leverage limited housing resources”; and support community partner organizations as they build their capacity to lead anti-displacement efforts [@bates_gentrification_2013, pp.18-25].

In addition to Bates' and Freeman's respective works, the literature review by Dr. Miriam Zuk et al describes the scholarship landscape on neighborhood change, gentrification, and displacement. This work explains the different conceptions and helps dispel any notion that there might be a universally accepted method for measuring any of these phenomena. Dr. Lei Ding and Dr. Jackelyn Hwang’s study of homeowner mobility in Philadelphia, which uses anonymized credit data from the Federal Reserve Bank of Philadelphia, illustrates the extraordinary degree of methodological ingenuity and access to private data that is required to “track” displacement at the household level [@ding_effects_2018].

Lastly, the City of Seattle’s 2016 “Growth and Equity” report illustrates a different methodology applied to part of the study area of this report [@city_of_seattle_seattle_2016]. Although Seattle’s assessment of displacement risk is also informed by Dr. Bates’ work in Portland, it uses a wider variety of indicators to produce an estimate of the relative _amount_ of risk rather than  the relative _type_ of susceptibility (i.e., a “continuous” scale rather than a “discrete” one).

### Key Terms Defined {-}

While the authors acknowledge the existing debate around these terms, for the sake of clarity this project uses the following definitions when referring to each term:

  - **Neighborhood Change:** a substantial shift in the socioeconomic and/or racial composition of a neighborhood’s residents and businesses along with the elements of the built environment that make up the neighborhood’s physical space.
  - **Gentrification:** the socioeconomic “upgrading” of a neighborhood’s demographics combined with a shift from low to high real estate values. While gentrification in the US context is often associated with the racial turnover of majority people of color neighborhoods [@miriam_zuk_gentrification_2015, pp.7-9], this project does not limit its definition of gentrification to racial demographic change.^[While this project doesn’t _require_ evidence of racial turnover in order for a neighborhood to be considered “gentrifying”, this study shows that increases in white, non-hispanic population are common in King County's gentrifying census tracts. See the #methods section for a detailed explanation of how this project defines gentrification]
  - **Displacement:** “the involuntary relocation of current residents or businesses from their current residence” [@city_of_seattle_seattle_2016, p.4]. This may be caused by the physical destruction of a home, the process of becoming “priced out” of a neighborhood, or the loss of an individual’s community and community-serving institutions. While studies show that the causality between gentrification and displacement is less clear than the popular narrative would suggest [@ding_gentrification_2016, p.6], this project nevertheless follows Bates' example of treating displacement as a negative outcome resulting from the the process of neighborhood gentrification [@bates_gentrification_2013, pp.9-11].

Other terms used throughout this report include:

  - **Census Tract:** according to the US Census Bureau, census tracts are "small, relatively permanent statistical subdivisions of a county or county equivalent and generally have a population size between 1,200 and 8,000 people, with an optimum size of 4,000 people" [@us_census_bureau_geography_nodate]. For the purposes of this project, census tracts are used as a geographic proxy for neighborhoods.
  - **Indicator:** an indicator is the "representation of statistical data for a specified time, place or any other relevant characteristic, corrected for at least one dimension (usually size) so as to allow for meaningful comparisons... It is a summary measure related to a key issue or phenomenon and derived from a series of observed facts" [@eurostat_eurostat_nodate]. For example, this project uses the percentage of a census tract's population that are low-income as an indicator of vulnerability to displacement.
  - **Model:** according to Professor Daniel Kaplan of Macalester College, a model is "a representation for a particular purpose" [@kaplan_statistical_2009, p.6]. This project builds a "classification model" of neighborhood change in order to better understand what displacement mitigation and neighborhood revitalization policies to consider adopting in specific neighborhoods throughout King County. The project's model is grounded in a conceptual understanding of how neighborhood change works [see @freeman_displacement_2005; @bates_gentrification_2013; and @miriam_zuk_gentrification_2015] and model's results are determined by the indicator data.^[A common aphorism in the field of statistics says that "all models are wrong, but some are useful" [@box_science_1976]. This phrase means that models are _necessarily_ a simplification of reality and, therefore, they should be judged not by their accuracy alone but by their ability to represent a phenomenon with enough accuracy to be useful. While the project's authors generally agree with this observation, we also believe that researchers have a responsibility to ask themselves "to _whom_ is this model useful?" and to consider the history of harm that has been done to marginalized communities by researchers and their models.]

