
# Discussion

## Partnership & Process Findings

Before discussing the project’s results (and their policy implications), it may be beneficial to consider the partnership and process that made the results possible.

Data-driven analyses like this one have no shortage of technical challenges to overcome but perhaps an even greater obstacle is the formation of the type of partnership that brings together the necessary expertise to complete the project responsibly. This project benefited from its genesis in the COO Evaluation and Advisory group, where staff members of community-based organizations helped to shape it with their knowledge of the three COO communities. Even though the project team had access to this pool of local expertise, the Pilot phase’s preliminary results did not reflect the lived reality of many of these communities. Through collaboration with the WCCDA in the revision stage, the project team was able to explore the inaccuracies of these findings and brainstorm solutions for gathering data that would better reflect the lived experiences of the communities. Although the method and data remain subject to many limitations, the project team is confident that the collaborative process enhanced the accuracy of the final results.

This experience underscores what might be the most significant finding of the project:
 

#### 1. The people from the communities most impacted by inequities are the ones who best understand the challenges that they face. They must, therefore, play a meaningful role in deciding what solutions to pursue. {-}

A classification model built with institutional data can be useful but its utility depends on the participation of members of the communities that are experiencing gentrification and displacement. Advisory groups, “ground-truthing” workshops, and flexibility on the part of the project team are all necessary components of a project like this one.

This project’s method relies on a small group of people using data from public institutions to produce information about many neighborhoods. The experience of undertaking this project has led its team to conclude that there is significant value in pursuing other research methods; ones that center the members of the most impacted communities and invest in their exploration of the issues that matter most to them. The approach known as “research justice” offers great potential in the pursuit of equitable community development and other related goals held by the Communities of Opportunity program and the government of King County.
^[For more information about research justice, see @jolivette_research_2015 and @coalition_of_communities_of_color_leading_2018]

#### 2. Involving community members and staff from community-based organizations during the ground-truthing workshops played a critical role in the project team’s effort to identify representative indicators. Ground truthing earlier in the project would have made the process more efficient. {-}

Initially, the question of whether to include ground-truthing workshops in the Pilot Project or to recommend them as next steps was a source of disagreement within the project team. After some back-and-forth debate, Puget Sound Sage prevailed with their argument that local contextual information is crucial not only for the research’s accuracy but also as a safeguard to prevent unintended harm to marginalized communities. This decision proved to be the right one, as these workshops provided feedback and criticism that significantly influenced the revision process and the project’s findings. Had there been efforts to engage directly with residents of the COO communities (aside from the EAG participants) earlier in the process, it is possible that a more accurate set of indicators would have been selected during the pilot and that the revision phase might not have been necessary. In any case, this project clearly benefited from the direct feedback of community members and the project team strongly recommends that other related projects apply this approach as well.

#### 3. Equitable, well-resourced, and accountable partnerships between researchers/consultants and community-based organizations/community members are necessary when conducting research that aims describe historically-marginalized communities. {-}

Given the major takeaway learned during Pilot stage, it became clear to Futurewise that they would need to partner and build stronger relationships with at least one of the communities that are experiencing gentrification. Since the WCCDA had expressed interest in offering more in-depth feedback, they became a natural ally in the search for better data sets to reflect their community. In October of 2017, Futurewise used its own resources to offer a graduate fellowship to Yen Baynes, a POC White Center community organizer and researcher.  This fellowship allowed Futurewise to build a closer relationship with the WCCDA because Ms. Baynes’ graduate thesis focused on her work with a WCCDA’s youth internship. Ms. Baynes joined the Neighborhood Change Typology (NCT) project in June of 2018, where she worked closely with Futurewise’s Data Analyst, Tiernan Martin, and WCCDA’s Data and Evaluation Manager, Dao Tran, to fine-tune the NCT by coordinating meetings in which both Futurewise and WCCDA staff worked together to identify indicators and data sets.

As a result, Futurewise was able to gain the insight necessary to complete the project.  There were many lessons learned throughout about how primarily White-led, issue-focused organizations such as Futurewise can work with POC-led, community-based organizations like the WCCDA.  One major lesson came near the end of this project as the WCCDA held Futurewise accountable by insisting that this report be written more collaboratively after a less-complete report was turned in without input from the WCCDA or Puget Sound Sage. The accountability required to form a more collaborative approach was reinforced by the equitable relationships that had been built throughout the project.  As a result, Futurewise learned the critical lesson about the importance of operationalizing accountability to the community members in research projects.


## Typology Findings

#### 1. Over 30% of the County’s neighborhoods are either experiencing gentrification or are susceptible to it. {-}

According to the project’s definition of “gentrification”, this means that a substantial portion of the County is experiencing an upward shift in socioeconomic demographics combined with housing market appreciation. Gentrification occurs in changing neighborhoods that are neither persistently low-income/low-value nor persistently high-income/high-value; in and of itself, it is not necessarily a bad thing.  

**However, history suggests that without community mobilization and strategic intervention by local governments, many community members in these changing neighborhoods will be forced to relocate just as the benefits of revitalization begin to emerge.**

The identification of 127 census tracts that meet the criteria for being at-risk or gentrifying suggests that substantial investment in anti-displacement and neighborhood revitalization initiatives should be undertaken. The large concentration of Early- and Mid-stage neighborhoods in the southwestern part of the county reaffirms what many of the “ground-truthing” workshop participants said: individuals, families, and whole communities are being “pushed“ out of Seattle’s South End neighborhoods and this shift seems to be rippling through the communities to the south. A similar effect may be occurring in some of Seattle’s North End neighborhoods near the city’s border with Shoreline, although the model suggests that a few of these communities are already in the Continued Loss stage of neighborhood change. 

Seattle’s Central Area neighborhood (also known as the Central District) shows a combination of Late and Continued Loss types - a result that reflects only the most recent part of the decades-long displacement of Seattle’s original African American community [@taylor_forging_1994; @mcgee_seattles_2007].

Lastly, the geographically-dispersed group of Continued Loss type neighborhoods east of Lake Washington is unexpected and warrants further investigation.

#### 2. The vast majority of Communities of Opportunity (COO) neighborhoods show signs of gentrification but the specific stages of gentrification vary. {-}

Of the COO neighborhoods, the most prevalent type is Early Type 1. This indicates that a neighborhood has relatively large populations that are vulnerable to displacement; has not yet seen a substantial demographic shift toward whiter, more affluent, better educated home owners; and still has low or moderate home values but is seeing high rates of short-term or medium-term home value appreciation. Put plainly, the neighborhoods are “on track” to gentrify and may soon experience significant displacement pressure (if they aren’t already).

The introduction of the additional indicators of appreciation (i.e., change in sale price per square foot and the percent of homes sold) improves the model’s ability to identify housing markets with high turnover rates.^[see Figure \@ref(fig:app-data-viz-comm-hous-hist) for a comparison of housing market indicators by COO community] The large number of Early Type 1 neighborhoods suggests that many places with high concentrations of vulnerable people are also the places where the housing market is “heating up”. This methodological change accounts for much of the different between the preliminary results produced during the Pilot phase and the final model results.

#### 3. Each COO community has at least one neighborhood undergoing the type of active gentrification associated with involuntary displacement. {-}

While evidence of substantial, gentrification-related demographic change is present in only 7 of the 34 COO community tracts, each of the communities has at least one such changing tract. As with the Early Type 1 neighborhoods, the new housing market appreciation indicators help the model to better identify Dynamic neighborhoods. While the demographic change indicators cannot by themselves be used as measures of displacement, they strongly suggest that vulnerable groups are being displaced from these neighborhoods. The Rainier Valley, which has four Dynamic tracts, should be treated as a community undergoing active gentrification and policies that are appropriate to this gentrification stage should be explored by community members and policymakers.

## Policy Implications

The goal of this project is to provide a consistent description of gentrification so that community leaders and policymakers can design effective intervention strategies that address and mitigate the displacement risk that marginalized communities face as King County continues to grow rapidly. The project adopts Dr. Bates’ neighborhood change typology framework (with modifications) and it also includes her “Policy Toolkit” to guide discussions about which tools and strategies might best address the needs of marginalized residents in COO communities. As Bates states, the decisions about which tools to use and how to prioritize scarce public resources are inherently political and therefore must be made in partnership with the most impacted communities [-@bates_gentrification_2013, p.56]. Additionally, one of the lessons learned as a result of this project is that equitable, well-resourced, and accountable partnerships with community-serving institutions are critical ingredients to success. The project team wishes to emphasize that this lesson applies both to research and to efforts to design or implement policies on a community’s behalf. Anti-displacement and community-stabilization policies that are generated by members of marginalized communities will have a much higher likelihood of sustained success than those that are created by external partners alone.

Prescriptive policy recommendations for specific communities are beyond the scope of this project but Dr. Bates’ “Policy Toolkit”, when paired with the typology results, may be useful in partnering with communities to assess appropriate policy alternatives. See [Appendix A: Bates' Policy Toolkit](#bates-policy-toolkit) for a list of the specific policies that Bates recommends for each stage of gentrification.

#### Final word on inclusive policy-making {-}

The importance of including people from the communities experiencing the disruptive impacts of displacement bears repeating. During the course of this project, the authors have witnessed first-hand how valuable and necessary it is to have local expertise “at the table“ when making these sort of decisions. The COO program is designed to embody this approach, as exemplified in their six strategies:

>  * Establishing community-based priorities
>  * Tapping into existing community expertise and leadership
>  * Strengthening community capacity for advocacy and to take on local challenges
>  * Systematizing a collaborative approach between communities and institutions
>  * Shaping policies to promote equity and positively impact our communities
>  * Bringing new resources into communities ^[For more details on the COO's approach see @noauthor_communities_nodate]

As mentioned in the [Guidance & Limitations section](#guidance-limitations) of the [Executive Summary](#executive-summary), if the results of this project are used to inform public policy, it is critical that they _complement_ the findings of direct community engagement - not replace them.