
# Conclusion

The disruptive threat of displacement is confronted by communities throughout King County. The Communities of Opportunity program provides a framework for the formation of public/private/community-based relationships that are uniquely capable of confronting systemic challenges like gentrification and involuntary displacement.

In 2016, a working group of community-based organizations from White Center, Rainier Valley, Seatac, and Tukwila decided to prioritize the monitoring of involuntary displacement in their neighborhoods. This led to a three-year endeavor with plenty of challenges along the way but ultimately the project arrived at its stated goal: a data-driven typology of neighborhood change that can inform current and future anti-displacement work.

The method, based on the work of Dr. Lisa Bates in Portland, OR; categorizes neighborhoods according to their gentrification stage (Early-, Mid-, and Late-stage) and the specific type of neighborhood change that they reflect. In 2016 the project team developed a preliminary model but it failed to identify the type of gentrification that was occurring in communities like White Center. The project began again in 2018, this time with a partnership between the initial project team (led by Futurewise) and the White Center Community Development Association. Together, the partnership developed a revised version of the neighborhood change typology that incorporates new indicators of housing market change.

The results of the project suggest that over 30% of the neighborhoods in the cities and unincorporated communities of King County are experiencing some stage of gentrification. Within the COO communities, the vast majority of neighborhoods are in either the Early- or Mid-stages; a result that reaffirms the many of the community members concerns and suggests some specific tools and strategies that should be investigated by community members and policymakers. The project also demonstrates the inherent limitations of data-driven methods that rely solely on datasets produced by centralized public institutions: they often exclude or mischaracterize the communities that are most marginalized. The lack of recent, county-wide rent price data is an example of how data availability reflects the power dynamics of a society, posing a challenge to this project and others like it.

While the findings of this project are limited by the method that produced them, there are clear applications of this knowledge in the development of anti-displacement and neighborhood revitalization strategies. The project team hopes that this information can serve as a foundation for subsequent projects and collaborations; preferably ones that experiment with different approaches that might better advance the opportunity of communities throughout King County.  Some of the same literature that informed this work also calls for providing communities, especially marginalized communities that include low income people and people of color, the wherewithal and the access to create, analyze and utilize their own data to inform policy decisions [@jolivette_research_2015]. Indeed, the project team found that throughout the process, it was the perspectives of community members that provided the most insight into how to improve the research. The project team suggests that when assessing next steps for researching and understanding gentrification and displacement in King County, the COO program should consider investing in educational and methodological resources for communities to embark on social science research that can yield community generated data. This would provide a critical missing link for better assessing policy solutions that seek to curb the negative impact of gentrification on these communities.
