# Tabular Data

```{r app-tabular-data-01, echo = FALSE, results='asis'}
lipsum::lipsum(n=1)
```

```{r app-tabular-data-comm-vuln-hist, fig.asp = 1, fig.cap='Vulnerability Indicators by COO Community (2013-2017)'}
# LOAD DATA ---------------------------------------------------------------

coorev18 <- readr::read_rds("data/model-all-20190305.rds") %>% 
  select(matches("GEOGRAPHY"), matches("COOREV18")) %>%  
  as_tibble() 

dat_wide <- coorev18 %>% select(matches("GEOGRAPHY"),
                 COOREV18_VULN_POC_EST_PCT_2013_2017,
                 COOREV18_VULN_LOWED_EST_PCT_2013_2017, 
                         COOREV18_VULN_LOWINCAMI_EST_PCT_2011_2015,
                 COOREV18_VULN_RENTHH_EST_PCT_2013_2017) 

dat_long <- dat_wide %>% 
  gather(COL, VAL, -matches("GEOGRAPHY")) %>% 
  mutate(YEAR = str_extract(COL,"\\d{4}_\\d{4}$")) %>% 
  mutate(VAR = case_when(
    str_detect(COL,"LOWED") ~ "% LOW-EDUCATION",
    str_detect(COL,"LOWINCAMI") ~ "% LOW-INCOME",
    str_detect(COL,"POC") ~ "% PEOPLE OF COLOR",
    str_detect(COL,"RENTHH") ~ "% RENTER"
  )) %>% 
  mutate(VAR = glue("{VAR} ({str_replace(YEAR,'_','-')})"))

dat_tr <- dat_long %>% 
  filter(GEOGRAPHY_TYPE %in% c("tract"))

dat_lines <- dat_long %>% 
  filter(GEOGRAPHY_TYPE %in% c("county", "community") | !is.na(GEOGRAPHY_COMMUNITY_NAME)) %>% 
  mutate(GEOG_TYPE_FCT = factor(GEOGRAPHY_TYPE,
                                levels = c("tract",
                                           "community",
                                           "county")))
dat_lines_by_comm <- dat_lines %>% 
  mutate(WC = VAL,
         RV = VAL,
         STC_TUK = VAL) %>% 
  select(-VAL) %>% 
  gather(GEOG_COMM, VAL, WC, RV, STC_TUK) %>% 
  nest(-GEOG_COMM) %>% 
  mutate(data = map2(data, GEOG_COMM, ~ filter(.x, GEOGRAPHY_COMMUNITY_ID %in% .y | GEOGRAPHY_TYPE %in% c("county", "community")))) %>% 
  unnest() %>% 
  mutate(GEOG_COMM = case_when(
    GEOG_COMM %in% "WC" ~ "White Center",
    GEOG_COMM %in% "RV" ~ "Rainier Valley",
    GEOG_COMM %in% "STC_TUK" ~ "Seatac/Tukwila"
  )) %>% 
  filter(GEOGRAPHY_TYPE %in% c("tract","county") | GEOG_COMM == GEOGRAPHY_NAME)


# PLOT --------------------------------------------------------------------

showtext_auto()

show_comm_hist <- function(x, y_axis_title, legend_position){  

  comm_name <- unique(x$GEOG_COMM)
  
  dat_tr %>% 
    ggplot2::ggplot(ggplot2::aes(x = VAL)) +
    ggplot2::scale_x_continuous(labels = scales::percent) +
    ggplot2::geom_histogram() +
    ggplot2::geom_vline(data = x, 
                        aes(xintercept = VAL, 
                            color = GEOG_TYPE_FCT, 
                            size = GEOG_TYPE_FCT, 
                            alpha = GEOG_TYPE_FCT,
                            linetype = GEOG_TYPE_FCT)) +
    scale_color_manual(values = c(colors_nct_list$Dynamic,
                                  colors_nct_list$Dynamic,
                                  colors_nct_list$Late)) +
    scale_size_manual(values = c(0.5,1,1)) +
    scale_alpha_manual(values = c(1,1,1)) +
    scale_linetype_manual(values = c(1,6,1)) + 
    ggplot2::facet_wrap(~ VAR, ncol = 1, scales = "fixed") +
    theme_nct_8 +
    labs(y = y_axis_title,
         x = "",
         title = comm_name) +
    theme(legend.position = legend_position,
          legend.direction="horizontal",
          legend.text.align = 0.5,
          legend.spacing.x = unit(12, "pt"), 
          legend.title = element_blank())
}
dat_list_by_comm <- group_split(dat_lines_by_comm, GEOG_COMM)

pmap(list(x = dat_list_by_comm,
            y_axis_title = c("# of Census Tracts","",""),
            legend_position = c("none","bottom","none")), 
     show_comm_hist) %>% 
  wrap_plots(nrow = 1) +
  plot_annotation(title = "Vulnerability Indicators by COO Community (2013-2017)",
                subtitle = "",
                caption = wrapper("Source: author's analysis of data from American Community Survey and HUD CHAS
                                  \nNote: The income indicator uses CHAS data, which lags behind the ACS data by two years'"),
                theme = theme_nct)
```

